import type { Metadata } from "next";
import "./globals.css";
import { Urbanist } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/providers/theme-provider";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body className={font.className}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
               <main>{children}</main>
               <Toaster />
            </ThemeProvider>
         </body>
      </html>
   );
}
